# Generated by Django 4.2 on 2023-04-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Futbolchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('transfer_narx', models.PositiveIntegerField()),
                ('yosh', models.PositiveIntegerField()),
                ('klub', models.CharField(max_length=30)),
                ('nafaqada', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=12)),
                ('yonalish', models.CharField(max_length=15)),
                ('daraja', models.IntegerField()),
                ('davomiylik', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=23)),
                ('yosh', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('jins', models.CharField(max_length=15)),
                ('bitiruvchi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Universitet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('talaba_soni', models.PositiveIntegerField()),
                ('ochilgan_sanasi', models.DateField()),
                ('sayt', models.URLField()),
                ('yillik', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('kasb', models.CharField(max_length=30)),
                ('yosh', models.PositiveIntegerField()),
                ('oylik', models.PositiveIntegerField()),
            ],
        ),
    ]
