# Generated by Django 4.2 on 2023-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talaba',
            name='ism',
            field=models.CharField(max_length=23, unique=True),
        ),
    ]
