# Generated by Django 4.2 on 2023-04-15 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_talaba_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('narx', models.PositiveIntegerField()),
                ('kelgan_sana', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Nashriyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=24)),
                ('manzil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('kitob_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.kitob')),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sotuvchi')),
            ],
        ),
        migrations.AddField(
            model_name='kitob',
            name='nashriyot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.nashriyot'),
        ),
    ]
