# Generated by Django 4.2 on 2023-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_alter_kitob_narx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitob',
            name='narx',
            field=models.CharField(max_length=100),
        ),
    ]
